name: CI-Release

on: [ push, pull_request ]

jobs:
  build-binary:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Docker Layer Caching
        uses: ScribeMD/docker-cache@0.5.0
        continue-on-error: true
        id: cache
        with:
          key: savemii-docker-cache-${{ hashFiles('DockerFile')}}
      - name: Build artifacts
        run: |
          docker build . --file Dockerfile --tag builder
          docker run --rm -v ${PWD}:/project builder make release -j$(nproc)
      - name: Upload Aroma version
        uses: actions/upload-artifact@v4
        with:
          name: SaveMiiModWUTPort-Aroma
          path: build/Aroma/*
          if-no-files-found: warn
      - name: Upload HBL version
        uses: actions/upload-artifact@v4
        with:
          name: SaveMiiModWUTPort-HBL
          path: build/HBL/*
          if-no-files-found: warn
